version: '3.4'
networks:
  ecs-local-network:
    # has to be the name below as the ecs-cli automatically uses this name (TODO: need to confirm)
    name: ecs-local-network
    driver: bridge
    ipam:
      config:
      - subnet: 169.254.170.0/24
        gateway: 169.254.170.1
services:
  ecs-local-endpoints:
    container_name: ecs-endpoint
    image: amazon/amazon-ecs-local-container-endpoints
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker
    environment:
    - IAM_ENDPOINT
    - STS_ENDPOINT

    - AWS_PROFILE=${ECS_ENDPOINT_AWS_PROFILE}

    - AWS_ACCESS_KEY_ID=${ECS_ENDPOINT_AWS_ACCESS_KEY_ID}
    - AWS_REGION=${ECS_ENDPOINT_AWS_REGION}
    - AWS_DEFAULT_REGION=${ECS_ENDPOINT_AWS_REGION}
    - AWS_SECRET_ACCESS_KEY=${ECS_ENDPOINT_AWS_SECRET_ACCESS_KEY}
    networks:
      ecs-local-network:
        # special IP address AWS clients automatically use to look up credential
        ipv4_address: 169.254.170.2
