version: '3.4'

services:
  ecs-local-endpoints:
    image: amazon/amazon-ecs-local-container-endpoints
    volumes:
    - ecs-local-aws-creds:/home/.aws

# contains AWS creds needed for ECS endpoint to vend credentials to task containers
volumes:
  ecs-local-aws-creds:
    name: ${ECS_AWS_CREDS_VOLUME_NAME}
    external: true
