version: '3.4'
networks:
  ecs-local-network:
    external: true
services:
  ecs-local-endpoints:
    image: amazon/amazon-ecs-local-container-endpoints
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker
    environment:
    - IAM_ENDPOINT
    - STS_ENDPOINT
    networks:
      ecs-local-network:
        ipv4_address: 169.254.170.2
  sleep:
    networks:
      ecs-local-network:
        ipv4_address: 169.254.170.3