name: Publish Docker image

on:
  release:
    types: [published]
  push:
    branches:
    - master
    tags:
    - ci
    - tests

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push Docker master image
      uses: docker/build-push-action@v3
      if: ${{ github.event_name == 'push' }}
      with:
        push: true
        tags: |-
          ${{ github.repository }}:latest
          ${{ github.repository }}:${{ github.sha }}
    - name: Build and push Docker release image
      uses: docker/build-push-action@v3
      if: ${{ github.event_name == 'release' }}
      with:
        push: true
        tags: ${{ github.repository }}:${{ github.event.release.tag_name }}
